[Tutorial](http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial#head-864862d3f2bb4c32f04260fac61eb4ef34788c4c)

In [25]:
import numpy as np

#line splitter
def sp(x="-", y=20):
    print(x*y)
    
ran = np.random.rand

The dots (...) represent as many colons as needed to produce a complete indexing tuple.  
For example, if x is a rank 5 array (i.e., it has 5 axes), then  
```
x[1,2,...] is equivalent to x[1,2,:,:,:],
x[...,3] to x[:,:,:,:,3] and
x[4,...,5,:] to x[4,:,:,5,:].
```

In [39]:
a = ran(2, 3)
b = ran(2, 3)
c = np.concatenate([a, b], -1)
print(c.shape)
print(c)

(2, 6)
[[0.60054848 0.78484613 0.65134828 0.1435338  0.80616109 0.25302254]
 [0.925334   0.61462913 0.49445052 0.57934554 0.88633389 0.04360018]]


In [44]:
np.random.uniform((2, 3))

array([1.52131292, 1.17583906])